name: Deploy Notebook

on:
  push:
    branches:
      - main
      - dev
  repository_dispatch:
    types: [trigger-panel-build-dev, trigger-panel-build-latest]


permissions:
  contents: write # Required to create releases
  actions: write # Required to access actions
  packages: write # Required to push Docker images

jobs:
  call-parent-build:
    uses: msd-live/devops-common/.github/workflows/notebook-image-build.yml@main
  
